blog/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^tiro_admin/', admin.site.urls),
    url(r'^', include('myBlog.urls', namespace='myBlog')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
]

blog/myBlog/urls.py
from django.conf.urls import url
from . import views
import django.views.static
from blog import settings

app_name = 'myBlog'

urlpatterns = [
    url(r'^$', views.page_view, name='index'),
    url(r'^pages/(?P<page>[0-9]+)/$', views.page_view, name='pages'),
    url(r'^tags/$', views.tags_view, name='tags'),
    url(r'^categories/$', views.categories_view, name='categories'),
    url(r'^articles/(?P<article_id>[0-9]+)/$', views.article_view, name='article'),
    url(r'^add/$', views.article_add_view, name='article_add'),
    url(r'^articles/(?P<article_id>[0-9]+)/edit/$', views.article_edit_view, name='article_edit'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^uploads/media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
    ]

blog/myBlog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

import markdown
# Create your models here.


class Category(models.Model):
    name = models.CharField('category name', max_length=16, unique=True)
    head_img = models.ImageField("Category head image", upload_to="images/head", blank=True, default=None)
    size = models.PositiveSmallIntegerField('tag size', default=1)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('tag name', max_length=16, unique=True)
    size = models.PositiveSmallIntegerField('tag size', default=1)

    def __str__(self):
        return self.name


class Comment(models.Model):
    name  = models.CharField('author', max_length=16)
    created_time = models.TimeField('comment created time', auto_now_add=True, null=True)
    content = models.TextField('comment content', blank=True)
    article = models.ForeignKey('Article', verbose_name='article comments', null=True)

    def __str__(self):
        return self.content


class Site(models.Model):
    EDITOR_CHOICE = (('Markdown', 'Markdown'), ('Rich text','Rich text',) )

    title = models.CharField('Site title', max_length=24, default="Your Blog")
    home_head_img = models.ImageField("Home head img", upload_to="images/head")
    home_url = models.CharField("Home url", max_length=48, default="http://127.0.0.1")
    home_desc = models.CharField("Home's page description", max_length=48, blank=True)
    article_num = models.IntegerField("Article num", default=10)
    editor = models.CharField("Editor type", max_length=24, choices=EDITOR_CHOICE, default='Markdown')
    tags_page_title = models.CharField("Tag's page title", max_length=48, default='Tags')
    tags_page_desc = models.CharField("Tag's page description", max_length=48, blank=True)
    tag_head_img = models.ImageField("Tag head img", upload_to="images/head")
    categories_page_title = models.CharField("Categories's page title", max_length=48, default='Categories')
    categories_page_desc = models.CharField("Categories's page description", max_length=48, blank=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField('Title', max_length=64)
    sub_title = models.CharField('Sub title', max_length=128, blank=True, default="")
    author = models.CharField('Author', max_length=16, default='Tiro')
    posted_time = models.DateTimeField("Posted time", auto_now_add=True, null=True)
    rich_text = RichTextUploadingField("Content")
    content = models.TextField("Content")
    head_img = models.ImageField('Head image', upload_to="images/head", blank=True, default=None)
    category = models.ForeignKey('Category', verbose_name="Category", null=True)
    tags = models.ManyToManyField('Tag', verbose_name='tags', blank=True)
    published  = models.BooleanField('Published', default=True)


    def save(self,*args, **kwargs):
        self.rich_text = markdown.markdown(self.content, 'codehilite')
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/myBlog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.


def page_view(request, page=1):
    article_list = Article.objects.filter(published=True)
    my_site = Site.objects.all()[0]
    paginator = Paginator(article_list, my_site.article_num)

    featured_tags = Tag.objects.order_by('size')[:3]
    featured_categories = Category.objects.order_by('size')[:3]

    try:
        artiles = paginator.page(page)
    except PageNotAnInteger:
        artiles = paginator.page(1)
    except EmptyPage:
        artiles = paginator.page(paginator.num_pages)

    return render(request, 'myBlog/pages.html',{
        'articles':artiles,
        'site':my_site,
        'featured_tags':featured_tags,
        'featured_categories':featured_categories
    })


def article_view(request, article_id):
    article = get_object_or_404(Article, pk=article_id, published=True)
    my_site = Site.objects.all()[0]
    return render(request, 'myBlog/article.html', {'article': article, 'site': my_site})


def article_add_view(request):
    return redirect("/tiro_admin/myBlog/article/add/")


def article_edit_view(request, article_id):
    return redirect("/tiro_admin/myBlog/article/%s/change"%article_id)


def categories_view(request):

    return render(request, 'myBlog/categories.html', {'categories': Category.objects.all(), 'site': Site.objects.all()[0]})


def tags_view(request):

    return render(request, 'myBlog/tags.html', {'tags': Tag.objects.all(), 'site': Site.objects.all()[0]})

blog/myBlog/templates/myBlog/article.html
{% load static %}
{% include 'myBlog/head.html'%}
<html>
<body ontouchstart="">
    {% include 'myBlog/nav.html' %}

    <!-- Post Header -->
    <style type="text/css">
        header.intro-header{
            position: relative;
            background-image: url('{% if article.head_img %}{{article.head_img.url}}{% elif article.category.head_img %}{{ article.category.head_img.url  }}{% else %}{{ site.home_head_img.url}}{% endif %}')
        }
    </style>
	<link rel="stylesheet" href="{% static 'myBlog/css/friendly.css' %}">

    <header class="intro-header" >
        <div class="header-mask"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">

                        <div class="tags">
                            <a class="tag" href="/categories/#{{ article.category.name }}" title="{{ article.category.name }}"> {{article.category.name}}</a>
                            {% for tag in article.tags.all %}
                            <a class="tag" href="/tags/#{{ tag.name }}" title="{{ tag.name }}">{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                        <h1>{{ article.title }}</h1>
                        <h2 class="subheading">{{ article.subtitle }}</h2>
                        <span class="meta">Posted by {{ article.author }} on {{ article.posted_time | date:'F j,Y'}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">

    <!-- Post Container -->
            <div class="
                col-lg-8 col-lg-offset-2
                col-md-10 col-md-offset-1
                post-container">

				{{ article.rich_text | safe}}

            </div>
        </div>
    </div>
</article>
{% include "myBlog/duoshuo.html" %}
{% include 'myBlog/footer.html' %}

<!-- jQuery -->
<script src="{% static 'myBlog/js/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'myBlog/js/bootstrap.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'myBlog/js/tiro_blog.min.js' %}"></script>


<!-- async load function -->
<script>
    function async(u, c) {
      var d = document, t = 'script',
          o = d.createElement(t),
          s = d.getElementsByTagName(t)[0];
      o.src = u;
      if (c) { o.addEventListener('load', function (e) { c(null, e); }, false); }
      s.parentNode.insertBefore(o, s);
    }
</script>


<!-- jquery.tagcloud.js -->
<script>
    // only load tagcloud.js in tag.html
    if($('#tag_cloud').length !== 0){
        async("{% static 'myBlog/js/jquery.tagcloud.js' %}",function(){
            $.fn.tagcloud.defaults = {
                //size: {start: 1, end: 1, unit: 'em'},
                color: {start: '#bbbbee', end: '#0085a1'},
            };
            $('#tag_cloud a').tagcloud();
        })
    }
</script>

<!--fastClick.js -->
<script>
    async("http://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function(){
        var $nav = document.querySelector("nav");
        if($nav) FastClick.attach($nav);
    })
</script>


</body>

</html>

blog/myBlog/templates/myBlog/categories.html
<!DOCTYPE html>
<html>
    {% include 'myBlog/head.html' %}
    {% load static %}
    <body ontouchstart="">
        {% include 'myBlog/nav.html'%}
        <!-- Page Header -->
        <header class="intro-header" style="background-image: url('{{site.home_head_img.url}}')">
           <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
                        <div class="site-heading">
                            <h1>{{site.categories_page_title}}</h1>
                            <!--<hr class="small">-->
                            <span class="subheading">{{site.categories_page_desc}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        <!-- Main Content -->
        <div class="container">
                    <!-- 标签云 -->
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <!-- 标签云 -->
                    <div id='tag_cloud' class="tags">
                        {% for category in categories %}
                        <a href="#{{ category.name }}" title="{{ category.name }}" rel="{{category.size}}">{{ category.name }}</a>
                        {% endfor %}
                    </div>

                    <!-- 标签列表 -->
                    {% for category in categories %}
                    <div class="one-tag-list">
                        <span class="fa fa-tag listing-seperator" id="{{ category.name }}">
                            <span class="tag-text">{{ category.name }}</span>
                        </span>
                        {% for article in category.article_set.all %}
						{% if article.published %}
                          <!-- <li class="listing-item">
                          <time datetime="{{ post.date | date:"%Y-%m-%d" }}">{{ post.date | date:"%Y-%m-%d" }}</time>
                          <a href="{{ post.url }}" title="{{ post.title }}">{{ post.title }}</a>
                          </li> -->
                         <div class="post-preview">
                            <a href="{% url 'myBlog:article' article.id %}">
                                <h2 class="post-title">
                                    {{ article.title }}
                                </h2>
                                {% if article.sub_title %}
                                <h3 class="post-subtitle">
                                    {{ article.sub_title }}
                                </h3>
                                {% endif %}
                            </a>
                            <!-- <p class="post-meta">{{ post.date | date:"%Y-%m-%d" }}</p> -->
                        </div>
                        <hr>
						{% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
        {% include 'myBlog/footer.html' %}
        <!-- jQuery -->
        <script src="{% static 'myBlog/js/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'myBlog/js/bootstrap.min.js' %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static 'myBlog/js/tiro_blog.min.js' %}"></script>


        <!-- async load function -->
        <script>
            function async(u, c) {
              var d = document, t = 'script',
                  o = d.createElement(t),
                  s = d.getElementsByTagName(t)[0];
              o.src = u;
              if (c) { o.addEventListener('load', function (e) { c(null, e); }, false); }
              s.parentNode.insertBefore(o, s);
            }
        </script>


        <!-- jquery.tagcloud.js -->
        <script>
            // only load tagcloud.js in tag.html
            if($('#tag_cloud').length !== 0){
                async("{% static 'myBlog/js/jquery.tagcloud.js' %}",function(){
                    $.fn.tagcloud.defaults = {
                        //size: {start: 1, end: 1, unit: 'em'},
                        color: {start: '#bbbbee', end: '#0085a1'},
                    };
                    $('#tag_cloud a').tagcloud();
                })
            }
        </script>

        <!--fastClick.js -->
        <script>
            async("http://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function(){
                var $nav = document.querySelector("nav");
                if($nav) FastClick.attach($nav);
            })
        </script>
    </body>
</html>

blog/myBlog/templates/myBlog/duoshuo.html
<!-- 多说评论框 start -->
    <div class="ds-thread" data-thread-key="{{ article.id }}" data-title="{{ article.title }}" data-url="{% url 'myBlog:article' article.id %}"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"tiro"};
    (function() {
        var ds = document.createElement('script');
        ds.type = 'text/javascript';ds.async = true;
        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
        ds.charset = 'UTF-8';
        (document.getElementsByTagName('head')[0]
         || document.getElementsByTagName('body')[0]).appendChild(ds);
    })();
    </script>
<!-- 多说公共JS代码 end -->

blog/myBlog/templates/myBlog/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">


                    <!--<li>-->
                        <!--<a target="_blank" href="#">-->
                            <!--<span class="fa-stack fa-lg">-->
                                <!--<i class="fa fa-circle fa-stack-2x"></i>-->
                                <!--<i class="fa  fa-stack-1x fa-inverse">知</i>-->
                            <!--</span>-->
                        <!--</a>-->
                    <!--</li>-->


                    <!--<li>-->
                        <!--<a target="_blank" href="#">-->
                            <!--<span class="fa-stack fa-lg">-->
                                <!--<i class="fa fa-circle fa-stack-2x"></i>-->
                                <!--<i class="fa fa-weibo fa-stack-1x fa-inverse"></i>-->
                            <!--</span>-->
                        <!--</a>-->
                    <!--</li>-->


                    <!--<li>-->
                        <!--<a target="_blank" href="#">-->
                            <!--<span class="fa-stack fa-lg">-->
                                <!--<i class="fa fa-circle fa-stack-2x"></i>-->
                                <!--<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>-->
                            <!--</span>-->
                        <!--</a>-->
                    <!--</li>-->


                    <li>
                        <a target="_blank" href="https://github.com/tiro-learner">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>

                </ul>
                <p class="copyright text-muted">
                    Copyright &copy; {{site.title}} 2016
                </p>
            </div>
        </div>
    </div>
</footer>

blog/myBlog/templates/myBlog/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-site-verification" content="xBT4GhYoi5qRD5tr338pgPM5OWHHIDR6mNg1a3euekI" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keyword"  content="">
    <link rel="shortcut icon" href="{% static 'myBlog/img/favicon.ico' %}">
    <title>{%if site.title%}{{site.title}}{%else%}{{Objects.site.title}}{%endif%}</title>


    <link rel="canonical" href="{{Object.site.home_url}}">

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'myBlog/css/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'myBlog/css/tiro_blog.min.css' %}">


    <!-- Custom Fonts -->
    <link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

blog/myBlog/templates/myBlog/nav.html
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">{{site.title}}</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id="blog_navbar">
            <div class="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>



                    <li>
                        <a href="/categories/">Categories</a>
                    </li>

                    <li>
                        <a href="/tags/">Tags</a>
                    </li>

                    <!--<li>-->
                        <!--<a href="/about/">About</a>-->
                    <!--</li>-->
                </ul>
            </div>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<script>
    // Drop Bootstarp low-performance Navbar
    // Use customize navbar with high-quality material design animation
    // in high-perf jank-free CSS3 implementation
    var $body   = document.body;
    var $toggle = document.querySelector('.navbar-toggle');
    var $navbar = document.querySelector('#blog_navbar');
    var $collapse = document.querySelector('.navbar-collapse');

    $toggle.addEventListener('click', handleMagic)
    function handleMagic(e){
        if ($navbar.className.indexOf('in') > 0) {
        // CLOSE
            $navbar.className = " ";
            // wait until animation end.
            setTimeout(function(){
                // prevent frequently toggle
                if($navbar.className.indexOf('in') < 0) {
                    $collapse.style.height = "0px"
                }
            },400)
        }else{
        // OPEN
            $collapse.style.height = "auto"
            $navbar.className += " in";
        }
    }
</script>

blog/myBlog/templates/myBlog/pages.html
<!DOCTYPE html>
<html>

{% include 'myBlog/head.html' %}
{% load static %}
<!-- hack iOS CSS :active style -->
<body ontouchstart="">

    <!-- Navigation -->
    {% include 'myBlog/nav.html'%}

    <!-- Page Header -->
<header class="intro-header" style="background-image: url('{{site.home_head_img.url}}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
                <div class="site-heading">
                    <h1>{{site.title}}</h1>
                    <!--<hr class="small">-->
                    <span class="subheading">{{site.home_desc}}</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
	<div class="row">

<!-- USE SIDEBAR -->
    <!-- Post Container -->
        <div class="
            col-lg-8 col-lg-offset-1
            col-md-8 col-md-offset-1
            col-sm-12
            col-xs-12
            post-container
        ">
           {% for article in articles %}
                {% if article.published %}
                    <div class="post-preview">
                        <a href="{% url 'myBlog:article' article.id %}">
                            <h2 class="post-title">
                                {{ article.title }}
                            </h2>
                            {% if article.sub_title %}
                            <h3 class="post-subtitle">
                                {{ article.sub_title }}
                            </h3>
                            {% endif %}
                            <div class="post-content-preview">
                                <!--{% load dehtml_parse %}-->
                                {{ article.rich_text | slice:"300" | dehtml}}
                            </div>
                        </a>
                        <p class="post-meta">
                            Posted by {{ article.author }} on {{ article.posted_time | date:"F j,Y"}}
                        </p>
                    </div>
                    <hr>
                {% endif %}
            {% endfor %}

        <!--Pager-->
        <ul class="pager">
            {% if articles.has_previous %}
            <li class="previous">
                <a href="/pages/{{articles.previous_page_number}}">&larr; Prev </a>
            </li>
            {% endif %}
            {% if articles.has_next %}
            <li class="next">
                <a href="/pages/{{articles.next_page_number}}">Next &rarr;</a>
            </li>
            {% endif %}
        </ul>
</div>
    <!-- Sidebar Container -->
            <div class="
                col-lg-3 col-lg-offset-0
                col-md-3 col-md-offset-0
                col-sm-12
                col-xs-12
                sidebar-container
            ">
                <!-- Featured Tags -->

                <section>
                    <hr class="hidden-sm hidden-xs">
                    <h5><a href="/tags/">FEATURED TAGS</a></h5>
                    <div class="tags">
                        {% for featured_tag in featured_tags %}
                                <a href="/tags/#{{featured_tag.name}}" title="{{featured_tag.name}}" rel="{{featured_tag.size}}">
                                    {{featured_tag.name}}
                                </a>
                        {% endfor %}
                    </div>
                </section>

                 <!-- Category -->
                 <section>
                    <hr class="hidden-sm hidden-xs">
                    <h5><a href="/categories/">FEATURED CATEGORIES</a></h5>
                    <div class="tags">
                        {% for featured_category in featured_categories %}
                                <a href="/categories/#{{featured_category.name}}" title="{{featured_category.name}}" rel="{{featured_category.size}}">
                                    {{featured_category.name}}
                                </a>
                        {% endfor %}
                    </div>
                </section>
    		</div>

	</div>
</div>


    <!-- Footer -->
{% include 'myBlog/footer.html' %}

<!-- jQuery -->
<script src="{% static 'myBlog/js/jquery.min.js' %}"></script>



<!-- async load function -->
<script>
    function async(u, c) {
      var d = document, t = 'script',
          o = d.createElement(t),
          s = d.getElementsByTagName(t)[0];
      o.src = u;
      if (c) { o.addEventListener('load', function (e) { c(null, e); }, false); }
      s.parentNode.insertBefore(o, s);
    }
</script>


<!-- jquery.tagcloud.js -->
<script>
    // only load tagcloud.js in tag.html
    if($('#tag_cloud').length !== 0){
        async("{% static 'myBlog/js/jquery.tagcloud.js' %}",function(){
            $.fn.tagcloud.defaults = {
                //size: {start: 1, end: 1, unit: 'em'},
                color: {start: '#bbbbee', end: '#0085a1'},
            };
            $('#tag_cloud a').tagcloud();
        })
    }
</script>

<!--fastClick.js -->
<script>
    async("http://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function(){
        var $nav = document.querySelector("nav");
        if($nav) FastClick.attach($nav);
    })
</script>

</body>

</html>

blog/myBlog/templates/myBlog/tags.html
<!DOCTYPE html>
<html>
    {% include 'myBlog/head.html' %}
    {% load static %}
    <body ontouchstart="">
        {% include 'myBlog/nav.html'%}
        <!-- Page Header -->
        <header class="intro-header" style="background-image: url('{% if site.tag_head_img.url %}{{site.tag_head_img.url}}{% else %}{{site.home_head_img.url}}{% endif %}')">
           <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
                        <div class="site-heading">
                            <h1>{{site.tags_page_title}}</h1>
                            <!--<hr class="small">-->
                            <span class="subheading">{{site.tags_page_desc}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        <!-- Main Content -->
        <div class="container">
            <div class="row">
		        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <!-- 标签云 -->
                    <div id='tag_cloud' class="tags">
                        {% for tag in tags %}
                        <a href="#{{ tag.name }}" title="{{ tag.name }}" rel="{{tag.size}}">{{ tag.name }}</a>
                        {% endfor %}
                    </div>

                    <!-- 标签列表 -->
                    {% for tag in tags %}
                    <div class="one-tag-list">
                        <span class="fa fa-tag listing-seperator" id="{{ tag.name }}">
                            <span class="tag-text">{{ tag.name }}</span>
                        </span>
                        {% for article in tag.article_set.all %}
						{% if article.published %}
                          <!-- <li class="listing-item">
                          <time datetime="{{ post.date | date:"%Y-%m-%d" }}">{{ post.date | date:"%Y-%m-%d" }}</time>
                          <a href="{{ post.url }}" title="{{ post.title }}">{{ post.title }}</a>
                          </li> -->
                         <div class="post-preview">
                            <a href="{% url 'myBlog:article' article.id %}">
                                <h2 class="post-title">
                                    {{ article.title }}
                                </h2>
                                {% if article.sub_title %}
                                <h3 class="post-subtitle">
                                    {{ article.sub_title }}
                                </h3>
                                {% endif %}
                            </a>
                            <!-- <p class="post-meta">{{ post.date | date:"%Y-%m-%d" }}</p> -->
                        </div>
                        <hr>
						{% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
        {% include 'myBlog/footer.html' %}
        <!-- jQuery -->
        <script src="{% static 'myBlog/js/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'myBlog/js/bootstrap.min.js' %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static 'myBlog/js/tiro_blog.min.js' %}"></script>


        <!-- async load function -->
        <script>
            function async(u, c) {
              var d = document, t = 'script',
                  o = d.createElement(t),
                  s = d.getElementsByTagName(t)[0];
              o.src = u;
              if (c) { o.addEventListener('load', function (e) { c(null, e); }, false); }
              s.parentNode.insertBefore(o, s);
            }
        </script>


        <!-- jquery.tagcloud.js -->
        <script>
            // only load tagcloud.js in tag.html
            if($('#tag_cloud').length !== 0){
                async("{% static 'myBlog/js/jquery.tagcloud.js' %}",function(){
                    $.fn.tagcloud.defaults = {
                        //size: {start: 1, end: 1, unit: 'em'},
                        color: {start: '#bbbbee', end: '#0085a1'},
                    };
                    $('#tag_cloud a').tagcloud();
                })
            }
        </script>

        <!--fastClick.js -->
        <script>
            async("http://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function(){
                var $nav = document.querySelector("nav");
                if($nav) FastClick.attach($nav);
            })
        </script>
    </body>
</html>

blog/templates/markdownx/widget.html
<div class="markdownx row">
    <div class="col-md-6">
        {{ markdownx_editor }}
    </div>
    <div class="col-md-6">
        <div class="markdownx-preview"></div>
    </div>
</div>
<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">